app:
  info:
    version: 1.0.0
server:
  port: 8081
spring:
  application:
    name: provider-service-${app.info.version}
    # redis 配置
  redis:
    host: 192.168.2.195
    port: 6379
    password:
    #连接超时时间（毫秒）
    timeout: 10000ms
    #连接池最大连接数（使用负值表示没有限制） 默认 8
    lettuce:
      pool:
        max-active: 16
        #连接池中的最大空闲连接 默认 8
        max-idle: 8
        #连接池最大阻塞等待时间,单位毫秒（使用负值表示没有限制） 默认 -1
        max-wait: 1000ms
        #连接池中的最小空闲连接 默认 0
        min-idle: 0
        shutdown-timeout: 100ms
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url-path: http://localhost:${server.port}/swagger-ui.html

