app:
  info:
    version: 1.0.0
server:
  port: 8081
spring:
  application:
    name: provider-service-${app.info.version}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/